# Docker Compose Build Optimization Configuration
# Reduces build time from 30min to <5min using BuildKit and advanced caching

# ===================================================================
#  Build Performance Anchors
# ===================================================================
x-build-cache: &build-cache
  cache_from:
    - ${REGISTRY:-}/${SERVICE_NAME:-app}:cache
  target: runtime

x-buildkit-config: &buildkit-config
  context: .
  cache_from:
    - type=local,src=/tmp/.buildx-cache
  cache_to:
    - type=local,dest=/tmp/.buildx-cache-new,mode=max
  platforms:
    - linux/amd64

# ===================================================================
#  Optimized Services with BuildKit Cache
# ===================================================================
services:
  # -------------------- Auth Service (Optimized) --------------------
  auth-service:
    build:
      <<: *buildkit-config
      dockerfile: ./services/auth-service/Dockerfile
      target: runtime
      args:
        BUILDKIT_INLINE_CACHE: 1
        SERVICE_NAME: auth-service
    image: mvp-auth-service:latest
    profiles: ["build"]

  # -------------------- Creator Hub Service (Optimized) --------------------
  creator-hub-service:
    build:
      <<: *buildkit-config
      dockerfile: ./services/creator-hub-service/Dockerfile
      target: runtime
      args:
        BUILDKIT_INLINE_CACHE: 1
        SERVICE_NAME: creator-hub-service
    image: mvp-creator-hub-service:latest
    profiles: ["build"]

  # -------------------- AI Engine Service (Highly Optimized) --------------------
  ai-engine-service:
    build:
      <<: *buildkit-config
      dockerfile: ./services/ai-engine-service/Dockerfile.optimized
      target: runtime
      args:
        BUILDKIT_INLINE_CACHE: 1
        SERVICE_NAME: ai-engine-service
        PYTHON_VERSION: 3.11
    image: mvp-ai-engine-service:latest
    profiles: ["build"]

  # -------------------- Channel Service (Optimized) --------------------
  channel-service:
    build:
      <<: *buildkit-config
      dockerfile: ./services/channel-service/Dockerfile
      target: runtime
      args:
        BUILDKIT_INLINE_CACHE: 1
        SERVICE_NAME: channel-service
    image: mvp-channel-service:latest
    profiles: ["build"]

# ===================================================================
#  Build Networks (Minimal for Build Process)
# ===================================================================
networks:
  build-network:
    driver: bridge