version: '3.8'

# Vault configuration for development
# This is a basic setup for development only - NOT for production use

services:
  vault:
    image: vault:1.15
    container_name: mvp-vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - ./scripts/vault-init.sh:/vault/init/vault-init.sh:ro
    command: |
      sh -c '
        vault server -dev -dev-root-token-id=dev-root-token -dev-listen-address=0.0.0.0:8200 &
        sleep 5
        export VAULT_ADDR=http://localhost:8200
        export VAULT_TOKEN=dev-root-token
        
        # Enable KV secrets engine
        vault secrets enable -path=secret kv-v2
        
        # Create basic development secrets
        vault kv put secret/mvp-coaching/database \
          username=postgres \
          password=postgres \
          host=postgres \
          port=5432 \
          database=mvp_coaching
        
        vault kv put secret/mvp-coaching/redis \
          url=redis://redis:6379
        
        vault kv put secret/mvp-coaching/jwt \
          secret_key=dev-jwt-secret-key-change-in-production \
          algorithm=HS256 \
          access_token_expire_minutes=1440 \
          refresh_token_expire_days=30
        
        vault kv put secret/mvp-coaching/ai \
          ollama_url=http://ollama:11434 \
          chromadb_url=http://chromadb:8000 \
          embedding_model=nomic-embed-text \
          chat_model=llama2:7b-chat
        
        echo "✅ Vault development secrets initialized"
        wait
      '
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mvp-network

volumes:
  vault_data:

networks:
  mvp-network:
    external: true